spring:

      jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
          "[hibernate.format_sql]": true
        datasource:
          driver-class-name: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
          username: taeseok
          password: wjd88512968